In [1]:
pip install nba_api

Collecting nba_api
  Downloading nba_api-1.4.1-py3-none-any.whl (261 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 261.7/261.7 kB 4.2 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: numpy<2.0.0,>=1.22.2 in /Users/don/anaconda3/lib/python3.10/site-packages (from nba_api) (1.23.5)
Collecting requests<3.0,>=2.31
  Downloading requests-2.31.0-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 6.0 MB/s eta 0:00:00
Requirement already satisfied: certifi<2024.0.0,>=2023.7.22 in /Users/don/anaconda3/lib/python3.10/site-packages (from nba_api) (2023.7.22)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/don/anaconda3/lib/python3.10/site-packages (from requests<3.0,>=2.31->nba_api) (1.26.14)
Requirement already satisfied: idna<4,>=2.5 in /Users/don/anaconda3/lib/python3.10/site-packages (from requests<3.0,>=2.31->nba_api) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/don/anaconda3/lib/python3.10/site-packages (from requests<3.0,>=2.31->nba_api) (2.0.4)
Installing collected packages: requests, nba_api
  Attempting uninstall: requests
    Found existing installation: requests 2.28.1
    Uninstalling requests-2.28.1:
      Successfully uninstalled requests-2.28.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
conda-repo-cli 1.0.41 requires requests_mock, which is not installed.
conda-repo-cli 1.0.41 requires clyent==1.2.1, but you have clyent 1.2.2 which is incompatible.
conda-repo-cli 1.0.41 requires nbformat==5.4.0, but you have nbformat 5.7.0 which is incompatible.
conda-repo-cli 1.0.41 requires requests==2.28.1, but you have requests 2.31.0 which is incompatible.
Successfully installed nba_api-1.4.1 requests-2.31.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
import nba_api
help(nba_api)

Help on package nba_api:

NAME
    nba_api

PACKAGE CONTENTS
    library (package)
    live (package)
    stats (package)

DATA
    name = 'nba_api'

FILE
    /Users/don/anaconda3/lib/python3.10/site-packages/nba_api/__init__.py

In [6]:
from nba_api.stats.endpoints import playercareerstats

# Nikola Jokić
career = playercareerstats.PlayerCareerStats(player_id='203999') 

# pandas data frames (optional: pip install pandas)
career.get_data_frames()[0]

# json
#career.get_json()

# dictionary
#career.get_dict()

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,203999,2015-16,00,1610612743,DEN,21.0,80,55,1733.0,307,...,0.811,181,379,560,189,79,50,104,208,796
1,203999,2016-17,00,1610612743,DEN,22.0,73,59,2038.0,494,...,0.825,212,506,718,359,61,55,171,214,1221
2,203999,2017-18,00,1610612743,DEN,23.0,75,73,2443.0,504,...,0.850,195,608,803,458,90,61,210,212,1385
3,203999,2018-19,00,1610612743,DEN,24.0,80,80,2504.0,616,...,0.821,228,637,865,580,108,55,248,228,1604
4,203999,2019-20,00,1610612743,DEN,25.0,73,73,2335.0,565,...,0.817,166,545,711,512,85,44,226,222,1456
5,203999,2020-21,00,1610612743,DEN,26.0,72,72,2488.0,732,...,0.868,205,575,780,599,95,48,222,192,1898
6,203999,2021-22,00,1610612743,DEN,27.0,74,74,2476.0,764,...,0.810,206,813,1019,584,109,63,281,191,2004
7,203999,2022-23,00,1610612743,DEN,28.0,69,69,2323.0,646,...,0.822,167,650,817,678,87,47,247,174,1690
8,203999,2023-24,00,1610612743,DEN,29.0,79,79,2737.0,822,...,0.817,223,753,976,708,108,68,237,194,2085

In [7]:
from nba_api.stats.static import players

# Get all players.
all_players = players.get_players()

# Find player by name, example: LeBron James
lebron = [player for player in all_players if player['full_name'] == 'LeBron James'][0]
print(lebron['id'])  # Prints LeBron's player_id

2544

In [8]:
from nba_api.stats.static import teams

# Get all teams.
all_teams = teams.get_teams()

# Find a team by name, example: Los Angeles Lakers
lakers = [team for team in all_teams if team['full_name'] == 'Los Angeles Lakers'][0]
print(lakers['id'])  # Prints the ID of the Lakers

1610612747

In [9]:
from nba_api.stats.endpoints import teamgamelog

# Fetch game logs for the Lakers
lakers_games = teamgamelog.TeamGameLog(team_id=lakers['id'])
print(lakers_games.get_data_frames()[0])  # Print the game logs as DataFrame

       Team_ID     Game_ID     GAME_DATE      MATCHUP WL   W   L  W_PCT  MIN  \
0   1610612747  0022301195  APR 14, 2024    LAL @ NOP  W  47  35  0.573  240
1   1610612747  0022301177  APR 12, 2024    LAL @ MEM  W  46  35  0.568  240
2   1610612747  0022301155  APR 09, 2024  LAL vs. GSW  L  45  35  0.563  240
3   1610612747  0022301143  APR 07, 2024  LAL vs. MIN  L  45  34  0.570  240
4   1610612747  0022301127  APR 06, 2024  LAL vs. CLE  W  45  33  0.577  240
..         ...         ...           ...          ... ..  ..  ..    ...  ...
77  1610612747  0022300127  NOV 01, 2023  LAL vs. LAC  W   3   2  0.600  265
78  1610612747  0022300111  OCT 30, 2023  LAL vs. ORL  W   2   2  0.500  240
79  1610612747  0022300100  OCT 29, 2023    LAL @ SAC  L   1   2  0.333  265
80  1610612747  0022300076  OCT 26, 2023  LAL vs. PHX  W   1   1  0.500  240
81  1610612747  0022300061  OCT 24, 2023    LAL @ DEN  L   0   1  0.000  240

    FGM  ...  FT_PCT  OREB  DREB  REB  AST  STL  BLK  TOV  PF  PTS
0    48  ...   0.944     7    32   39   32   12    3   14  13  124
1    42  ...   0.765    10    29   39   25    5    6   19  17  123
2    44  ...   0.833    10    30   40   31    8    3    7  14  120
3    39  ...   0.875    10    31   41   27   10    2   15  14  117
4    45  ...   0.625     6    34   40   30   11   11   17  12  116
..  ...  ...     ...   ...   ...  ...  ...  ...  ...  ...  ..  ...
77   46  ...   0.750     9    42   51   28   10    9   14  24  130
78   42  ...   0.778     3    37   40   28    7   10   16  17  106
79   43  ...   0.765     8    45   53   27    4    4   12  22  127
80   36  ...   0.793     8    34   42   24   14    7   16  23  100
81   41  ...   0.750    13    31   44   23    5    4   11  18  107

[82 rows x 27 columns]

In [ ]:
from nba_api.stats.endpoints import playercareerstats
from nba_api.stats.endpoints import commonplayerinfo
from nba_api.stats.static import teams
from nba_api.stats.endpoints import teamplyerdashboard
from nba_api.stats.endpoints import teamgamelog
from nba_api.stats.endpoints import teamyearbyyearstats
from nba_api.stats.endpoints import boxscoretraditionalv2
from nba_api.stats.endpoints import playbyplay
from nba_api.live.nba.endpoints import scoreboard
from nba_api.stats.endpoints import draftcombinestats
from nba_api.stats.endpoints import draftcombinedrillresults
from nba_api.stats.endpoints import leagueleaders

In [12]:
from nba_api.live.nba.endpoints import scoreboard

# Today's Score Board
games = scoreboard.ScoreBoard()

# json
games.get_json()

# dictionary
games.get_dict()

{'meta': {'version': 1,
  'request': 'https://nba-prod-us-east-1-mediaops-stats.s3.amazonaws.com/NBA/liveData/scoreboard/todaysScoreboard_00.json',
  'time': '2024-04-17 10:24:12.2412',
  'code': 200},
 'scoreboard': {'gameDate': '2024-04-17',
  'leagueId': '00',
  'leagueName': 'National Basketball Association',
  'games': [{'gameId': '0052300111',
    'gameCode': '20240417/ATLCHI',
    'gameStatus': 2,
    'gameStatusText': 'Q2 11:13',
    'period': 2,
    'gameClock': 'PT11M13.00S',
    'gameTimeUTC': '2024-04-18T01:30:00Z',
    'gameEt': '2024-04-17T21:30:00-04:00',
    'regulationPeriods': 4,
    'ifNecessary': False,
    'seriesGameNumber': '',
    'gameLabel': None,
    'gameSubLabel': None,
    'seriesText': 'Loser eliminated',
    'seriesConference': '',
    'poRoundDesc': '',
    'gameSubtype': '',
    'homeTeam': {'teamId': 1610612741,
     'teamName': 'Bulls',
     'teamCity': 'Chicago',
     'teamTricode': 'CHI',
     'wins': 39,
     'losses': 43,
     'score': 40,
     'seed': 9,
     'inBonus': '0',
     'timeoutsRemaining': 4,
     'periods': [{'period': 1, 'periodType': 'REGULAR', 'score': 40},
      {'period': 2, 'periodType': 'REGULAR', 'score': 0},
      {'period': 3, 'periodType': 'REGULAR', 'score': 0},
      {'period': 4, 'periodType': 'REGULAR', 'score': 0}]},
    'awayTeam': {'teamId': 1610612737,
     'teamName': 'Hawks',
     'teamCity': 'Atlanta',
     'teamTricode': 'ATL',
     'wins': 36,
     'losses': 46,
     'score': 28,
     'seed': 10,
     'inBonus': '0',
     'timeoutsRemaining': 6,
     'periods': [{'period': 1, 'periodType': 'REGULAR', 'score': 22},
      {'period': 2, 'periodType': 'REGULAR', 'score': 6},
      {'period': 3, 'periodType': 'REGULAR', 'score': 0},
      {'period': 4, 'periodType': 'REGULAR', 'score': 0}]},
    'gameLeaders': {'homeLeaders': {'personId': 201942,
      'name': 'DeMar DeRozan',
      'jerseyNum': '11',
      'position': 'GF',
      'teamTricode': 'CHI',
      'playerSlug': 'demar-derozan',
      'points': 11,
      'rebounds': 1,
      'assists': 5},
     'awayLeaders': {'personId': 1627749,
      'name': 'Dejounte Murray',
      'jerseyNum': '5',
      'position': 'G',
      'teamTricode': 'ATL',
      'playerSlug': 'dejounte-murray',
      'points': 14,
      'rebounds': 2,
      'assists': 2}},
    'pbOdds': {'team': None, 'odds': 0.0, 'suspended': 0}},
   {'gameId': '0052300101',
    'gameCode': '20240417/MIAPHI',
    'gameStatus': 3,
    'gameStatusText': 'Final',
    'period': 4,
    'gameClock': '',
    'gameTimeUTC': '2024-04-17T23:00:00Z',
    'gameEt': '2024-04-17T19:00:00Z',
    'regulationPeriods': 4,
    'ifNecessary': False,
    'seriesGameNumber': '',
    'gameLabel': 'East Play-In',
    'gameSubLabel': '',
    'seriesText': 'PHI clinch 7 seed',
    'seriesConference': '',
    'poRoundDesc': '',
    'gameSubtype': '',
    'homeTeam': {'teamId': 1610612755,
     'teamName': '76ers',
     'teamCity': 'Philadelphia',
     'teamTricode': 'PHI',
     'wins': 1,
     'losses': 0,
     'score': 105,
     'seed': 7,
     'inBonus': None,
     'timeoutsRemaining': 0,
     'periods': [{'period': 1, 'periodType': 'REGULAR', 'score': 22},
      {'period': 2, 'periodType': 'REGULAR', 'score': 17},
      {'period': 3, 'periodType': 'REGULAR', 'score': 30},
      {'period': 4, 'periodType': 'REGULAR', 'score': 36}]},
    'awayTeam': {'teamId': 1610612748,
     'teamName': 'Heat',
     'teamCity': 'Miami',
     'teamTricode': 'MIA',
     'wins': 0,
     'losses': 1,
     'score': 104,
     'seed': 8,
     'inBonus': None,
     'timeoutsRemaining': 0,
     'periods': [{'period': 1, 'periodType': 'REGULAR', 'score': 23},
      {'period': 2, 'periodType': 'REGULAR', 'score': 28},
      {'period': 3, 'periodType': 'REGULAR', 'score': 23},
      {'period': 4, 'periodType': 'REGULAR', 'score': 30}]},
    'gameLeaders': {'homeLeaders': {'personId': 203954,
      'name': 'Joel Embiid',
      'jerseyNum': '21',
      'position': 'C-F',
      'teamTricode': 'PHI',
      'playerSlug': None,
      'points': 23,
      'rebounds': 15,
      'assists': 5},
     'awayLeaders': {'personId': 1629639,
      'name': 'Tyler Herro',
      'jerseyNum': '14',
      'position': 'G',
      'teamTricode': 'MIA',
      'playerSlug': None,
      'points': 25,
      'rebounds': 2,
      'assists': 9}},
    'pbOdds': {'team': None, 'odds': 0.0, 'suspended': 0}}]}}